# permissions for end users to edit mastodons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: magout
    app.kubernetes.io/managed-by: kustomize
  name: mastodon-editor-role
rules:
- apiGroups:
  - magout.anqou.net
  resources:
  - mastodons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - magout.anqou.net
  resources:
  - mastodons/status
  verbs:
  - get
