# fullnameOverride: ""

mastodonVersion:
  image: ghcr.io/mastodon/mastodon:v4.2.12
  streamingImage: ghcr.io/mastodon/mastodon:v4.2.12

gateway:
  serverName: "" # CHANGE HERE
  deploy:
    replicas: 1
    image: nginx:1
    resources: {}
  service:
    type: ClusterIP
    port: 80

mastodonServer:
  sidekiq:
    replicas: 1
    labels: {}
    annotations: {}
    envFrom: [] # CHANGE HERE
    resources: {}
    periodicRestart: {}
    #periodicRestart:
    #  schedule: "0 0 * * *"
    #  timeZone: UTC
  web:
    replicas: 1
    labels: {}
    annotations: {}
    envFrom: [] # CHANGE HERE
    resources: {}
    periodicRestart: {}
  streaming:
    replicas: 1
    labels: {}
    annotations: {}
    envFrom: [] # CHANGE HERE
    resources: {}
    periodicRestart: {}
