# fullnameOverride: ""

mastodonVersion:
  # image: ghcr.io/mastodon/mastodon:latest
  # streamingImage: ghcr.io/mastodon/mastodon-streaming:latest

gateway:
  # serverName: "example.com"
  deploy:
    replicaCount: 1
    image: nginx:latest
    resources: {}
  service:
    type: ClusterIP
    port: 80

mastodonServer:
  sidekiq:
    # replicas: 1
    # labels: {}
    # annotations: {}
    # envFrom: {}
    # resources: {}
    # periodicRestart:
    #   schedule: "0 0 * * *"
    #   timeZone: UTC
  web:
    # replicas: 1
    # labels: {}
    # annotations: {}
    # envFrom: {}
    # resources: {}
    # periodicRestart:
    #   schedule: "0 0 * * *"
    #   timeZone: UTC
  streaming:
    # replicas: 1
    # labels: {}
    # annotations: {}
    # envFrom: {}
    # resources: {}
    # periodicRestart:
    #   schedule: "0 0 * * *"
    #   timeZone: UTC
