name: "End-to-end test"
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  e2e-test:
    name: "test"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_version: ["1.31.0", "1.30.4", "1.29.8"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make -C test/e2e test
